#!/bin/bash

# Generated by GitHub Copilot (GPT-4o)
# Test script for invoice generator iterations
# This script runs multiple tests to validate the generator and save outputs

echo "=== Invoice Generator Test Suite ==="
echo "Running multiple iterations to test and improve the generator..."

# Create timestamp for this test run
TIMESTAMP=$(date +%s)
TEST_BASE="test-suite-$TIMESTAMP"

echo "Test run timestamp: $TIMESTAMP"
echo "Base name: $TEST_BASE"

# Test 1: Basic functionality test
echo ""
echo "Test 1: Basic functionality test..."
node generator.js cover_letter_and_invoice_example.yaml "${TEST_BASE}-basic" || {
    echo "ERROR: Basic test failed!"
    exit 1
}

# Test 2: Edge case - verify calculation
echo ""
echo "Test 2: Verifying calculations..."
node generator.js cover_letter_and_invoice_example.yaml "${TEST_BASE}-calc" || {
    echo "ERROR: Calculation test failed!"
    exit 1
}

# Test 3: Performance test
echo ""
echo "Test 3: Performance test..."
START_TIME=$(date +%s%N)
node generator.js cover_letter_and_invoice_example.yaml "${TEST_BASE}-perf" > /dev/null 2>&1
END_TIME=$(date +%s%N)
DURATION=$(((END_TIME - START_TIME) / 1000000))
echo "Generation time: ${DURATION}ms"

# List all generated files
echo ""
echo "=== Generated Files ==="
ls -la output/${TEST_BASE}* 2>/dev/null || echo "No files found"

# Check logs
echo ""
echo "=== Recent Logs ==="
ls -la logs/*.log | tail -3

echo ""
echo "=== Test Suite Complete ==="
echo "All tests passed successfully!"
echo "Files are saved in the output/ directory"
echo "Logs are saved in the logs/ directory"
