// This file was generated by Copilot, a large language model, to provide test cases for the PDF generation functionality.
// The test cases validate that the generated PDF documents match the expected results based on the input YAML data.

const fs = require('fs');
const path = require('path');
const { generatePDF } = require('../src/pdfGenerator');
const yaml = require('js-yaml');

describe('PDF Generation Tests', () => {
    let testData;

    beforeAll(() => {
        // Load test data from YAML file
        const yamlFilePath = path.join(__dirname, 'testData.yaml');
        testData = yaml.load(fs.readFileSync(yamlFilePath, 'utf8'));
    });

    test('should generate a valid invoice PDF', async () => {
        const invoicePDF = await generatePDF(testData.invoice);
        const expectedPDFPath = path.join(__dirname, 'testInvoice.pdf');

        // Compare generated PDF with expected PDF
        expect(invoicePDF).toEqual(expect.arrayContaining(fs.readFileSync(expectedPDFPath)));
    });

    test('should generate a valid cover letter PDF', async () => {
        const coverLetterPDF = await generatePDF(testData.coverLetter);
        const expectedPDFPath = path.join(__dirname, 'testCoverLetter.pdf');

        // Compare generated PDF with expected PDF
        expect(coverLetterPDF).toEqual(expect.arrayContaining(fs.readFileSync(expectedPDFPath)));
    });
});