/**
 * Generated by GitHub Copilot (GPT-4)
 * Invoice Generator - Main Module
 * 
 * Main entry point for the Invoice Generator library.
 * Exports the core classes for programmatic use.
 */

const InvoiceGenerator = require('./InvoiceGenerator');
const InvoiceParser = require('./InvoiceParser');
const InvoiceCLI = require('./cli');

module.exports = {
    InvoiceGenerator,
    InvoiceParser,
    InvoiceCLI,
    
    /**
     * Convenience function to generate an invoice from a file
     * @param {string} inputFile - Path to the input file
     * @param {string} outputFile - Path for the output PDF
     * @param {Object} options - Generator options
     */
    async generateFromFile(inputFile, outputFile, options = {}) {
        const parser = new InvoiceParser();
        const generator = new InvoiceGenerator(options);
        
        const invoiceData = parser.parseFile(inputFile);
        return await generator.generateInvoice(invoiceData, outputFile);
    },
    
    /**
     * Convenience function to generate an invoice from data
     * @param {Object} invoiceData - Structured invoice data
     * @param {string} outputFile - Path for the output PDF
     * @param {Object} options - Generator options
     */
    async generateFromData(invoiceData, outputFile, options = {}) {
        const generator = new InvoiceGenerator(options);
        return await generator.generateInvoice(invoiceData, outputFile);
    }
};